name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: test
    runs-on: [self-hosted, linux]
    steps:
      - run: echo "GitHub Workspace:" $GITHUB_WORKSPACE
      - run: echo "Self-hosted runner:" $(hostname) $(whoami)